import {
  FaCar,
  FaChair,
  FaPagelines,
  FaCarrot,
  FaFeatherAlt,
  FaLaptop,
  FaLightbulb,
  FaTshirt,
  FaCannabis,
  FaMobile,
  FaGlasses,
  FaShoppingBag,
  FaGem,
} from 'react-icons/fa';
import {
  GiFurBoot,
  GiLargeDress,
  GiShirt,
  GiTabiBoot,
  GiWatch,
} from 'react-icons/gi';
// eslint-disable-next-line import/no-anonymous-default-export
export default [
  { name: 'automotive', icon: FaCar },
  { name: 'fragrances', icon: FaPagelines },
  { name: 'furniture', icon: FaChair },
  { name: 'groceries', icon: FaCarrot },
  { name: 'home-decoration', icon: FaFeatherAlt },
  { name: 'laptops', icon: FaLaptop },
  { name: 'lighting', icon: FaLightbulb },
  { name: 'mens shirts', icon: FaTshirt },
  { name: 'mens shoes', icon: GiTabiBoot },
  { name: 'mens watches', icon: GiWatch },
  { name: 'motorcycle', icon: FaCar },
  { name: 'skincare', icon: FaCannabis },
  { name: 'smartphones', icon: FaMobile },
  { name: 'sunglasses', icon: FaGlasses },
  { name: 'tops', icon: GiShirt },
  { name: 'womens bags', icon: FaShoppingBag },
  { name: 'womens dresses', icon: GiLargeDress },
  { name: 'womens jewellery', icon: FaGem },
  { name: 'womens shoes', icon: GiFurBoot },
  { name: 'womens watches', icon: GiWatch },
];
